### ISSUE TITLE
NativeScript analytics

### ISSUE THREAD

**Issue by sitefinitysteve** [skypanther/mobileframeworks#5]
I was going to PR it, but just unsure how you'd prefer it structured :D

Nativescript Analytics is only paid if you go with the telerik platform.  You can opt to use Google analytics, or Firebase or any other free plugin, you aren't tied to telerik in any way.

**Comment by m1ga** [comment]
I think it refers to analytics provided by the developer itself. 
E.g. Titanium has modules for other analytic tools too but Appcelerator offers paid analytics you can use.

**Comment by sitefinitysteve** [comment]
Hmmm, could be misleading to someone using this to make a decision though.  Like you don't *need* to touch anything telerik to use NativeScript, could just pull down the CLI and never even have a telerik account.  

It it was a pure Tooling comparison then it should be "Via Plugin"

I mean just food for thought, good article!

**Comment by m1ga** [comment]
You are right, there should be a subtext "provided by the developer" and a footnote with "free alternatives can be used via plugin" or so

**Comment by sitefinitysteve** [comment]
Will close, thanks again for this

**Comment by skypanther** [comment]
I'm happy to add the note as you have described. So, reopening to add something like: _You are right, there should be a subtext "provided by the developer" and a footnote with "free alternatives can be used via plugin" or so_

**Comment by skypanther** [comment]
Resolved by #7
